language: node_js

node_js:
- "node"

git:
  autocrlf: true

branches:
  only:
  - master

install:
  - npm install

script:
  - npm run deploy

before_deploy: "echo 'node_modules' > .gitignore"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_ACCESS
  keep_history: true
  local_dir: .
  name: BetterDiscord Deployment
  target_branch: gh-pages
  on:
    branch: master